; PlatformIO Project Configuration File
;
; Projet : Pulsmon / ESP32-S3 Display
; Cible : ESP32-S3 via board custom boards/jc3248w535c.json
; Environnements :
;   - pulsmon-esp32s3-display     : build principal, sans flags debug Pulsmon
;   - pulsmon-esp32s3-display-dev : build dev, avec flags debug Pulsmon
;
; SDKConfig attendus :
;   - sdkconfig.pulsmon-esp32s3-display
;   - sdkconfig.pulsmon-esp32s3-display-dev

[platformio]
description = Pulsmon ESP32-S3 Display
default_envs = pulsmon-esp32s3-display
boards_dir = boards
data_dir = littlefs
lib_dir = libraries
src_dir = src

[env]
platform = espressif32@6.6.0
board = jc3248w535c
framework = espidf
monitor_filters = esp32_exception_decoder

board_build.filesystem = littlefs
board_build.partitions = partitions.csv

lib_deps =
	lvgl/lvgl@^8.4.0

build_flags =
	-D LV_CONF_PATH=${PROJECT_DIR}/src/lv_conf.h

[debug]
build_flags =
	-D LOG_LOCAL_LEVEL=ESP_LOG_VERBOSE
	-D PULSEMON_DEBUG=1
	-D PULSEMON_NEWS_DEBUG=1
	-D PULSEMON_LATENCY_DEBUG=0
	-D PULSEMON_UI_WARN_MS=80
	-D PULSEMON_HTTP_WARN_MS=400
	-D PULSEMON_SCREENSHOT_DEBUG=0
	-D PULSEMON_SCREENSHOT_INTERVAL_MS=30000
	-D PULSEMON_SCREENSHOT_DIR=\"/sdcard/pulsemon/captures\"

[env:pulsmon-esp32s3-display]
build_type = release

[env:pulsmon-esp32s3-display-dev]
build_type = debug
build_flags =
	${env.build_flags}
	${debug.build_flags}
