#ifndef PRINTER_CONFIG_H
#define PRINTER_CONFIG_H

#define PRINTER_HTTP_PORT 80
#define PRINTER_MQTT_PORT 1883
#define PRINTER_HTTP_TIMEOUT_MS 4000
#define PRINTER_MQTT_TIMEOUT_MS 5000
#define PRINTER_POLL_INTERVAL_MS 5000
#define PRINTER_RETRY_INTERVAL_MS 5000
#define PRINTER_APP_PING_INTERVAL_MS 30000

#endif
