#ifndef PULSEMON_API_CONFIG_H
#define PULSEMON_API_CONFIG_H

#define PULSEMON_API_DEFAULT_HOST "192.168.0.10"
#define PULSEMON_API_DEFAULT_PORT 8000

#define PULSEMON_HTTP_TIMEOUT_MS 1500
#define PULSEMON_DASHBOARD_POLL_MS 1000

#endif
