#ifndef WIFI_CONFIG_H
#define WIFI_CONFIG_H

#define PULSEMON_WIFI_AP_SSID "PulseMon-Setup"
#define PULSEMON_WIFI_AP_PASSWORD ""
#define PULSEMON_WIFI_MAX_RETRY 10
#define PULSEMON_WIFI_SCAN_MAX_RESULTS 20

#endif
