#ifndef WIFI_CONFIG_H
#define WIFI_CONFIG_H

#define PULSEMON_WIFI_AP_SSID "PulseMon-Setup"
#define PULSEMON_WIFI_AP_PASSWORD ""
#define PULSEMON_WIFI_AP_IPV4 "192.168.4.1"
#define PULSEMON_WIFI_MAX_RETRY 10
#define PULSEMON_WIFI_SCAN_MAX_RESULTS 20
#define PULSEMON_WIFI_LOCAL_TRIGGER_HOLD_MS 5000U
#define PULSEMON_WIFI_LOCAL_TRIGGER_HOTSPOT_PX 64
#define PULSEMON_WIFI_MANUAL_CONFIG_TIMEOUT_MS 300000U

#endif
